# Generated by Django 4.1.5 on 2023-02-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=10)),
                ('Marca', models.CharField(max_length=10)),
                ('Modelo', models.CharField(max_length=20)),
                ('Uso', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=10)),
                ('Modelo', models.CharField(max_length=20)),
                ('Uso', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Televisores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=10)),
                ('Marca', models.CharField(max_length=10)),
                ('Modelo', models.CharField(max_length=20)),
                ('Uso', models.BooleanField(default=False)),
            ],
        ),
    ]
